# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "An Eleventy blog you can publish to Fastly for free."
language = "javascript"
manifest_version = 3
name = "sueglasgow-11ty-to-compute"
service_id = "v27AZ58wh6WegV0uVEJcwn"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.sueglasgow-11ty-to-compute-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.sueglasgow-11ty-to-compute-content]
